ubc_layout_config.overview:
  path: 'admin/config/user-interface/ubc-layout'
  defaults:
    _controller:  '\Drupal\ubc_layout_config\Controller\Overview::description'
    _title: 'UBC Layout Options'
  requirements:
    _permission: 'administer site configuration'

ubc_layout_config.ubc_general_settings:
  path: 'admin/config/user-interface/ubc-layout/general-settings-form'
  defaults:
    _form:  '\Drupal\ubc_layout_config\Form\GeneralSettingsForm'
    _title: 'UBC General Layout Options'
  requirements:
    _permission: 'administer site configuration'

ubc_layout_config.ubc_homepage_settings:
  path: 'admin/config/user-interface/ubc-layout/homepage-form'
  defaults:
    _form: '\Drupal\ubc_layout_config\Form\HomepageForm'
    _title: 'UBC Homepage Settings'
  requirements:
    _permission: 'administer site configuration'

ubc_layout_config.ubc_landing_page_settings:
  path: 'admin/config/user-interface/ubc-layout/landing-page-form'
  defaults:
    _form: '\Drupal\ubc_layout_config\Form\LandingPageForm'
    _title: 'UBC Landing Page Settings'
  requirements:
    _permission: 'administer site configuration'

ubc_layout_config.ubc_announcement_settings:
  path: 'admin/config/user-interface/ubc-layout/announcement-form'
  defaults:
    _form: '\Drupal\ubc_layout_config\Form\AnnouncementForm'
    _title: 'UBC Announcement Settings'
  requirements:
    _permission: 'administer site configuration'

ubc_layout_config.ubc_page_settings:
  path: 'admin/config/user-interface/ubc-layout/page-form'
  defaults:
    _form: '\Drupal\ubc_layout_config\Form\PageForm'
    _title: 'UBC Page Settings'
  requirements:
    _permission: 'administer site configuration'
