name: UBC Editor Configuration
type: module
description: This module defines default configuration for Drupal's WYSIWYG, cKeditor.
package: UBC Web Services
dependencies:
  - drupal:ckeditor
  - drupal:breakpoint
  - drupal:responsive_image
  - inline_responsive_images:inline_responsive_images
  - ubc_ckeditor_widgets:ubc_ckeditor_widgets
version: '8.x-1.0'
core: '8.x'
project: 'ubc_editor_config'
